### ISSUE TITLE
最后一步报错

### ISSUE THREAD

**Issue by fu-jw** [nezhahq/Nezha-Telegram-Bot-V1#3]
在绑定账号时的最后一步，写数据库时报错，提示语法错误

具体报错：
```
2024-12-15 09:32:42,887 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/ext/_application.py", line 1124, in process_update
    await coroutine
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/ext/_conversationhandler.py", line 825, in handle_update
    new_state: object = await handler.handle_update(
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "bot.py", line 149, in bind_alias
    await db.add_user(telegram_id, username, password, dashboard_url, alias)
  File "/root/Nezha-Telegram-Bot/database.py", line 46, in add_user
    cursor = await db.execute('''
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 190, in execute
    cursor = await self._execute(self._conn.execute, sql, parameters)
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 133, in _execute
    return await future
  File "/root/Nezha-Telegram-Bot/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 106, in run
    result = function()
sqlite3.OperationalError: near "RETURNING": syntax error
```

**Comment by cantoblanco** [comment]
#4 此PR已修复此问题

**Comment by naiba** [comment]
此问题已在 PR #4 中修复。关闭此 issue。
